### PR TITLE
Add support for testing CephFS and ceph-proxy.

### PR DESCRIPTION
**Pull request by freyes**
This change allows to use ceph-mon or ceph-proxy for testing ceph-fs.

Closes-Bug: https://pad.lv/1922195

### CODE REVIEW

**Comment by freyes** [comment]
There is a full successful run of this patch for ceph-proxy at 

And there is a patch to exercise ceph-fs charm using this PR at https://review.opendev.org/c/openstack/charm-ceph-fs/+/806936 , this one hasn't completed a successful CI run yet, because undercloud issues so far, will update this PR once a successful run has completed.

**Comment by ajkavanagh** [comment]
@freyes I'm guessing we still want to merge this; the associated gerrit review *almost* passed, but needs rebasing and (ServerStack permitting) re-running the checks.

**Comment by freyes** [comment]
The associated charm patch ( https://review.opendev.org/c/openstack/charm-ceph-proxy/+/784212 ) was merged, this PR was left open. This is producing failures in the gate https://review.opendev.org/c/openstack/charm-ceph-proxy/+/888828

```
2023-08-03 20:30:29.654264 | focal-medium | 2023-08-03 20:30:29 [INFO] TIMEOUT: Workloads didn't reach acceptable status:
2023-08-03 20:30:29.654890 | focal-medium | 2023-08-03 20:30:29 [INFO] Timed out waiting for 'ubuntu/0'. The workload status message is '' which is not one of '['ready', 'Ready', 'Unit is ready']'
2023-08-03 20:30:29.654947 | focal-medium | 2023-08-03 20:30:29 [INFO] Timed out waiting for 'ubuntu/1'. The workload status message is '' which is not one of '['ready', 'Ready', 'Unit is ready']'
```

**Review by sabaini — APPROVED** [review]
lgtm -- many thanks for picking this up!

**Pull request merged**
