### PR TITLE
octavia: Grant role to ensure access to LBAASv2 API

### PR DESCRIPTION
**Pull request by fnordahl**
Starting with OpenStack Wallaby the LBAASv2 API will require
authentication with system scoped token unless the user has
the 'load-balancer_admin' role.

Grant role on test setup, and remove it again on clean-up.

### CODE REVIEW

**Review by AurelienLourot — APPROVED** [review]

**Comment by AurelienLourot** [comment]
Charm reviews making use of it:
- https://review.opendev.org/c/openstack/charm-octavia/+/778991
- https://review.opendev.org/c/openstack/charm-octavia/+/796701

**Review by AurelienLourot — CHANGES_REQUESTED** [review]
I believe this func-test-pr doesn't work on Stein and causes:

```
PENDING_DELETE
Revoke "load-balancer_admin" role from current user with "project" scope...
Revoke "load-balancer_admin" role from current user with "project" scope...
Revoke "load-balancer_admin" role from current user with "project" scope...
ERROR
======================================================================
ERROR: test_create_loadbalancer (zaza.openstack.charm_tests.octavia.tests.LBAASv2Test)
Create load balancer.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/octavia/tests.py", line 211, in resource_cleanup
    LBAAS_ADMIN_ROLE)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/octavia/tests.py", line 96, in revoke_role_current_user
    keystone_client, keystone_session, 'revoke', role_name, scope=scope)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/octavia/tests.py", line 76, in _op_role_current_user
    **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneclient/v3/roles.py", line 390, in revoke
    **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneclient/base.py", line 86, in func
    return f(*args, **new_kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneclient/base.py", line 480, in delete
    self.build_url(dict_args_in_out=kwargs))
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneclient/base.py", line 246, in _delete
    resp, body = self.client.delete(url, **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 410, in delete
    return self.request(url, 'DELETE', **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 554, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 257, in request
    return self.session.request(url, method, **kwargs)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/keystoneauth1/session.py", line 986, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.NotFound: Could not find role assignment with role: de779da3b93648f58106a98baf5d896e, user or group: a53c41d8f49c44ebbf16b723f184bc18, project, domain, or system: ced77cd4738d4d4ab449b6c5a12dc6a9. (HTTP 404) (Request-ID: req-7f3edcfd-ac45-4be2-a0a1-c1b9cdfd7f72)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/test_utils.py", line 120, in tearDown
    self.resource_cleanup()
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/tenacity/__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/tenacity/__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-octavia/build/builds/octavia/.tox/func-target/lib/python3.6/site-packages/tenacity/__init__.py", line 379, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f2bb1e4afd0 state=finished raised NotFound>]
----------------------------------------------------------------------
Ran 1 test in 1430.639s
FAILED
```

**Comment by fnordahl** [comment]
@AurelienLourot it does pass for Stein most of the time, so I guess this could be a Keystone caching issue or something like that. But since the transient issue only presents itself at Stein, and the change is required only for Wallaby and onward, I guess the best course of action would be to version fence the change of behavior in the test.

**Review by AurelienLourot — APPROVED** [review]
LGTM, thanks, waiting for successful CI on https://review.opendev.org/c/openstack/charm-octavia/+/778991

**Comment by AurelienLourot** [comment]
Keeping the branch for now because we're landing https://review.opendev.org/c/openstack/charm-octavia/+/778991 but https://review.opendev.org/c/openstack/charm-octavia/+/796701 also points to this func-test-pr still

**Pull request merged**
