### PR TITLE
Clean up newly created instances if faulty

### PR DESCRIPTION
**Pull request by AurelienLourot**
CI results: https://review.opendev.org/#/c/754533

### CODE REVIEW

**Review by fnordahl — COMMENTED** [review]
The higher level launch_guest helper already removes instances before retrying creation, so my only question would be, would you be able to use that helper or is this for a different issue?

https://github.com/openstack-charmers/zaza-openstack-tests/blob/20263394c91d3be4328223b674ad9dbeab834361/zaza/openstack/charm_tests/test_utils.py#L553-L561

**Comment by AurelienLourot** [comment]
@fnordahl true, good idea

**Comment by AurelienLourot** [comment]
@fnordahl we're already using `launch_guest()` actually: https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_full/openstack/charm-manila/754533/1/7100/consoleText.test_charm_func_full_10195.txt

So my root cause analysis must be wrong. I'll dig more.

**Comment by AurelienLourot** [comment]
Ah no I see, the cleanup you're mentioning is not at the right place so it did not happen. Will fix.

**Review by ChrisMacNaughton — APPROVED** [review]

**Pull request merged**
