### PR TITLE
Check blocked ovn-chassis units with bad config

### PR DESCRIPTION
**Pull request by gabrielcocenza**
LP bug#1919481 [0] needs to have a func-test to check if units can
handle bad bridge-interface-mappings configuration and set units
workload to block state and return to active state with good config.
    
[0] https://bugs.launchpad.net/charm-ovn-chassis/+bug/1919481

### CODE REVIEW

**Review by fnordahl — CHANGES_REQUESTED** [review]
Thank you for your work on this. What the test achieves looks good, but it's implementation is a bit repetitive. I would love to see the same test utilize the common config_changed helper:

https://github.com/openstack-charmers/zaza-openstack-tests/blob/57ca7c68e0c90f64545a3ec6b7d8cea9a1347dbe/zaza/openstack/charm_tests/test_utils.py#L265

There are many examples of its use in this repository.

**Comment by gabrielcocenza** [comment]
> Thank you for your work on this. What the test achieves looks good, but it's implementation is a bit repetitive. I would love to see the same test utilize the common config_changed helper:
> 
> https://github.com/openstack-charmers/zaza-openstack-tests/blob/57ca7c68e0c90f64545a3ec6b7d8cea9a1347dbe/zaza/openstack/charm_tests/test_utils.py#L265
> 
> There are many examples of its use in this repository.

I actually tried to use the `config_change` before doing this way, but I faced a problem that the states that I want to test are not the same as the `target_deploy_status` used in this function and they were hanging forever.

https://github.com/openstack-charmers/zaza-openstack-tests/blob/57ca7c68e0c90f64545a3ec6b7d8cea9a1347dbe/zaza/openstack/charm_tests/test_utils.py#L328-L330

Should I try to change the attribute `test_config` before running this test?

**Comment by fnordahl** [comment]
> Should I try to change the attribute `test_config` before running this test?

Yes, that would work, there is an example of that here:
https://github.com/openstack-charmers/zaza-openstack-tests/blob/57ca7c68e0c90f64545a3ec6b7d8cea9a1347dbe/zaza/openstack/charm_tests/ceph/tests.py#L992-L1016

**Comment by gabrielcocenza** [comment]
Apparently, everything went well with this way you showed.

https://pastebin.canonical.com/p/YnNQrvdvHb/

Thanks for the tip.

**Review by fnordahl — APPROVED** [review]
LGTM, thanks!

**Comment by fnordahl** [comment]
Now that #608 has merged the tests should pass once this PR is rebased.

**Review by fnordahl — APPROVED** [review]
LGTM, thanks! Validated in https://review.opendev.org/c/x/charm-ovn-chassis/+/801525

**Pull request merged**
