### PR TITLE
Add func tests for iscsi-connector charm

### PR DESCRIPTION
**Pull request by camille-rodriguez**
The new charm iscsi-connector is a subordinate charm that configures and connect a unit to an iscsi backend. 
The charm is hosted on Launchpad and will be maintained by BootStack. 
The PR for the full charm is here : https://code.launchpad.net/~camille.rodriguez/charm-iscsi-connector/+git/charm-iscsi-connector/+merge/388393
The Feature Spec is here : https://docs.google.com/document/d/1WLKqSbmqoNDG5ytW3n6vh_imUE4AmG44RRY4wKP3BmE/edit#

### CODE REVIEW

**Comment by ryan-beisner** [comment]
> As discussed offline, I think this should live in a different repo owned by BootStack (maybe call it `zaza-bootstack-tests`?). Then the charm can point to that repo in its `test-requirements.txt`

Strictly speaking I think you are correct.  But this one is close enough to ceph-iscsi in test overlap that I can see the case for it being included here.

If this were graylog or some other thing, I'd advocate more strongly for a separate test library (as a plugin like zaza-openstack-tests).

**Comment by ChrisMacNaughton** [comment]
unless we actually merge the ceph-iscsi and iscsi tests, I disagree. They are different test/setup code for different charms

**Comment by ryan-beisner** [comment]
> unless we actually merge the ceph-iscsi and iscsi tests, I disagree. They are different test/setup code for different charms

I see this charm as a potentially valuable test fixture for ceph-iscsi, which is the nature of my comment.  But that doesn't necessarily mean its test library needs to live here.

Ultimately, given the need for a different organization to directly manage the tests, I'd stick with Aurelien's original review.

**Comment by camille-rodriguez** [comment]
Closing the pull request, as the tests will live locally with the charm https://code.launchpad.net/~bootstack-charmers/charm-iscsi-connector/+git/charm-iscsi-connector/+ref/master

**Pull request closed without merging**
