### PR TITLE
Make network, images, and keypair names envars

### PR DESCRIPTION
**Pull request by Basdbruijne**
Remove hardcoded image names, network names, and keypair names and move them to environment variables

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Hi @Basdbruijne  - I think you'll need to rebase this on master, as there have been some changes merged that conflict with these changes (mostly around tox 4 and fixing the GitHub CI system.

**Comment by Basdbruijne** [comment]
Thanks @ajkavanagh, it's rebased. Can you give it another look?

**Review by freyes — CHANGES_REQUESTED** [review]
The changes LGTM, although can you document this (new) set of environment variables in a table in the README file?

**Review by freyes — APPROVED** [review]
LGTM

**Pull request merged**
