### PR TITLE
Add COS integration testing for ceph-mon

### PR DESCRIPTION
**Pull request by sabaini**
Test retrieval of metrics, alert rules and dashboards

### CODE REVIEW

**Comment by sabaini** [comment]
https://review.opendev.org/c/openstack/charm-ceph-mon/+/926155

**Review by lmlg — APPROVED** [review]
lgtm, cheers!

**Comment by nobuto-m** [comment]
@sabaini In https://review.opendev.org/c/openstack/charm-ceph-mon/+/926204, I don't see any output related to `COSIntegrationTest`. Am I missing something?

```
$ grep 'Running Test zaza' job-output.txt 
2024-08-13 16:28:47.495649 | focal-medium | 2024-08-13 16:28:47 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CheckPoolTypes ##
2024-08-13 16:28:49.846339 | focal-medium | 2024-08-13 16:28:49 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephLowLevelTest ##
2024-08-13 16:29:11.498140 | focal-medium | 2024-08-13 16:29:11 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephTest ##
2024-08-13 16:30:24.156484 | focal-medium | 2024-08-13 16:30:24 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.osd.tests.SecurityTest ##
2024-08-13 16:30:25.477339 | focal-medium | 2024-08-13 16:30:25 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephPrometheusTest ##
2024-08-13 16:30:26.609841 | focal-medium | 2024-08-13 16:30:26 [INFO] ## Running Test zaza.charm_tests.lifecycle.tests.UpgradeCharmsToPath;ceph-mon ##
2024-08-13 16:30:32.776860 | focal-medium | 2024-08-13 16:30:32 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephMonJujuPersistent ##
2024-08-13 16:31:44.873439 | focal-medium | 2024-08-13 16:31:44 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CheckPoolTypes ##
2024-08-13 16:31:46.129491 | focal-medium | 2024-08-13 16:31:46 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephLowLevelTest ##
2024-08-13 16:32:07.839153 | focal-medium | 2024-08-13 16:32:07 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephTest ##
2024-08-13 16:33:18.514145 | focal-medium | 2024-08-13 16:33:18 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.osd.tests.SecurityTest ##
2024-08-13 16:33:19.840755 | focal-medium | 2024-08-13 16:33:19 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephPrometheusTest ##
2024-08-13 16:33:21.012524 | focal-medium | 2024-08-13 16:33:21 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephAuthTest ##
2024-08-13 16:33:32.803361 | focal-medium | 2024-08-13 16:33:32 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephMonActionsTest ##
2024-08-13 16:33:57.210691 | focal-medium | 2024-08-13 16:33:57 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.mon.tests.CephPermissionUpgradeTest ##
2024-08-13 16:35:25.463498 | focal-medium | 2024-08-13 16:35:25 [INFO] ## Running Test zaza.openstack.charm_tests.ceph.tests.CephMonKeyRotationTests ##
```

**Comment by sabaini** [comment]
These tests are only being run if there's grafana-agent present. Due to resource constraints we don't plan to run them in the regular CI but will add a COS model + grafana-agent into the SQA tests

**Pull request merged**
