### PR TITLE
Add fixes for the rbd-mirror tests

### PR DESCRIPTION
**Pull request by lmlg**

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
This is being validated on https://review.opendev.org/c/openstack/charm-ceph-rbd-mirror/+/852667

**Comment by UtkarshBhatthere** [comment]
https://review.opendev.org/c/openstack/charm-ceph-rbd-mirror/+/852667 was abandoned in favour of https://review.opendev.org/c/openstack/charm-ceph-rbd-mirror/+/850173

**Comment by jadonn** [comment]
It looks like code was merged in https://review.opendev.org/c/openstack/charm-ceph-rbd-mirror/+/885163 related to this PR. Do you all still need this PR?

**Comment by lmlg** [comment]
Not needed anymore.

**Comment by jadonn** [comment]
Thank you very much, Luciano! We'll close this PR then.

**Pull request closed without merging**
