### PR TITLE
Fix ceph-dashboard SAML tests

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
This PR ensures that the SAML tests are using a fully valid IDP
metadata (Ceph's dashboard doesn't report its validity until SAML
features are used), as well as using TLS in the requests, in addition
to some cleanups here and there.

Cherry-picked (and then rebased) from https://github.com/openstack-charmers/zaza-openstack-tests/pull/762

### CODE REVIEW

**Comment by ChrisMacNaughton** [comment]
This is being validated in https://review.opendev.org/c/openstack/charm-ceph-dashboard/+/840934

**Comment by jadonn** [comment]
@UtkarshBhatthere or @lmlg Do you all still need this PR? According to the comments in https://review.opendev.org/c/openstack/charm-ceph-dashboard/+/840934:

"this change has likely bee superseded by time, as the stable/quincy.2 branch is now pushing to the quincy charmhub track"

I wanted to check in with you all that this PR is still needed or if we can close it safely.

**Comment by lmlg** [comment]
the comments are correct, this PR is not needed anymore.

**Comment by jadonn** [comment]
Thank you, Luciano! We'll get this PR closed, then.

**Pull request closed without merging**
