### PR TITLE
Add ceilometer-agent tests

### PR DESCRIPTION
**Pull request by AurelienLourot**
https://launchpad.net/bugs/1927277

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Validating here: https://review.opendev.org/c/openstack/charm-ceilometer-agent/+/803359

**Comment by AurelienLourot** [comment]
Hitting https://bugs.launchpad.net/charm-ceilometer-agent/+bug/1938884 - investigating

**Comment by AurelienLourot** [comment]
Worked around in [the Wallaby test bundles](https://review.opendev.org/c/openstack/charm-ceilometer-agent/+/803359). The CI should now turn green.

**Review by ajkavanagh — APPROVED** [review]
LGTM

**Pull request merged**
